# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b8573e817cdc0075776426b7e2ea420a1ec341a8394e2c408e6ae911cabdefa015ed17c135333b3a14591f941e3e685a07c72eec58e0f9cdb00f5ef486fbbce
  auth0_client_id: 87LRyzwpfbQ8fpT2J4DGEm1pxCR41WGl
  auth0_client_secret: GWPA7WKuBxoo3IUDYk69mPBJrxQhGp-agRZMQ6yZc6auUnrY-cxQ_Q6_Qs8we6ok


test:
  secret_key_base: eb6a1e637814e7fc1f435711e0115511222df734cdec9439e15bdaae0b92012b72a32f27d4cadbbac49c8381a866f37f10c8c90d7e4646cc00fac003cbbf0776


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth0_client_id: 87LRyzwpfbQ8fpT2J4DGEm1pxCR41WGl
  auth0_client_secret: GWPA7WKuBxoo3IUDYk69mPBJrxQhGp-agRZMQ6yZc6auUnrY-cxQ_Q6_Qs8we6ok
